# Browser Configuration (chrome / firefox)
browser=chrome

# Application URL
base.url=https://www.saucedemo.com/

# Implicit Wait (seconds)
implicit.wait=10

# Explicit Wait (seconds)
explicit.wait=15

# Headless mode (true / false)
headless=false

# API Base URL
api.base.url=https://simple-books-api.click
api.authentication.url=/api-clients/

# Test Users
valid.username=standard_user
valid.password=secret_sauce
locked.username=locked_out_user
invalid.username=invalid_user
invalid.password=wrong_password
